config/routes.rb
require 'subdomain'

Rails.application.routes.draw do
	get '/submit-image-to-profile' => 'photos#submit'
	post '/accept-image-to-profile' => 'photos#accept'

	resources :news
	resources :links
	resources :credits
	resources :entries
	resources :posts
	resources :topics
	resources :videos
	resources :screensavers
	resources :wallpapers

	devise_for :users, controllers: { 
		sessions: 'users/sessions', 
		registrations: 'users/registrations', 
		passwords: 'users/passwords' 
	}
	devise_for :admins, controllers: { 
		sessions: 'admins/sessions', 
		registrations: 'admins/registrations', 
		passwords: 'admins/passwords' 
	}

	resources :movies
	resources :tracks
	resources :photos
	resources :albums
#	resources :profiles
	
	# match '', to: 'blogs#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
	
#	constraints(Subdomain) do
#	    get '/' => 'profiles#show'
	    
	   
	    #resources :posts do
	    #  collection do
	    #    get :search
	    #  end
	    #end

		resources :profiles do
			resources :messages
	#		post 'contact', to: 'messages#create', as: 'create_message'
	#		get 'contact', to: 'messages#new', as: 'new_message'
		  	resources :movies
			resources :photos
			resources :albums do 
				resources :tracks
			end
			get 'filmography'
			get 'biography'
			get 'media'
			resources :wallpapers
			resources :screensavers
			resources :videos
			resources :topics do
				resources :posts
			end
			resources :entries
	 		resources :credits do
	 			get 'in'
	 			get 'out'
	 		end
			resources :links
			resources :news
		end

#	  end 

	# resources :profiles, constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' } do
	
	get 'home/index' #, :defaults => { :format => 'html' }
	get 'home/order' #, :defaults => { :format => 'html' }

	root 'profiles#index' #, :defaults => { :format => 'html' }

  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
	belongs_to :profile
	belongs_to :user
	has_many :posts

	def post_total
		total = 1
		total += posts.count
	end

	def last_post
		return self if posts.count <= 0
		return posts.last
	end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :set_profile, except: [:create]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :verify_owner!, only: [:edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = @profile.topics
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
    @topic.profile_id = @profile.id if !@profile.nil?
    @topic.user = User.find(current_user["id"]) if current_user
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @topic.user = User.find(current_user["id"]) if current_user
   
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def set_profile
      @profile = !@topic.nil? ? @topic.profile : Profile.find(params[:profile_id])
    end

    def verify_owner!
      puts "[[[]]] verify_owner! #{@topic.user.id} == #{current_user["id"]}"

      if @topic.user.id != current_user["id"]
        flash[:notice] = "User is not the owner of this topic"
        redirect_to root_path
      end 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:label, :profile_id, :message)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
	def format_last_post(item)
		html = ''

		if item.class == Topic
			html += 'by ' + item.user.name
			html += ' ' + link_to('view', profile_topic_path(@profile, item))
		else
			html += 'by ' + item.user.name
			html += ' ' + link_to('view', profile_topic_path(@profile, item.topic))
		end 

		html
	end
end

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label, id: :topic_label %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message, id: :topic_message %>
  </div>

  <%= form.hidden_field :profile_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<% title "Edit Forum Topic for #{@profile.name}'s Profile" %>
<% description "Edit forum topic for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, forum, topic" %>
<table class="activity-with-menu">
  <tbody>
    <tr>
      <td class="activity-with-menu-left">
        <h1><%= link_to @profile.name, profile_path(@profile) %></h1>
        <h2><%= link_to 'Forum', profile_topics_path(@profile) %></h2>
        <h3>Editing Topic</h3>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', profile_topics_path %>

      </td>
      <td class="activity-with-menu-right">
        <%= render 'profiles/menu', profile: @profile %>
      </td>
    </tr>
  </tbody>
</table>

app/views/topics/index.html.erb
<% title "View All Forum Topics for #{@profile.name}'s Profile" %>
<% description "View all forum topics for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, forum, topic" %>
<table class="activity-with-menu">
  <tbody>
    <tr>
      <td class="activity-with-menu-left" >
        <h1><%= link_to @profile.name, profile_path(@profile) %></h1>
        <h2><%= link_to 'Forum', profile_topics_path(@profile) %></h2>

<p id="notice"><%= notice %></p>

<%= link_to 'Create a New Topic', new_profile_topic_path(@profile) %>
<br /><br />

<p>
Forum's on Purefame are meant to discuss in depth topics down to a conclusion. Anyone can start a new topic to discuss with the open community.   
</p>

<table width="100%" border="1">
  <thead>
    <tr>
      <th align="left" width="74%">Topic</th>
      <th align="left" width="1%">Posts</th>
      <th align="left" width="25%">Last Post</th>
    </tr>
  </thead>

  <tbody>
    <% if !@topics.any? %>
      <tr>
        <td colspan="3">No topics yet</td>
      </tr>
    <% end %>
    <% @topics.each do |topic| %>
      <% cache ["v1", topic] do %>
      <tr>
        <td>
          <%= link_to topic.label, profile_topic_posts_path(@profile, topic) %>  
        </td>
        <td>
          <%= topic.post_total %>
        </td>
        <td>
          <%= format_last_post(topic.last_post).html_safe %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>


     </td>
      <td class="activity-with-menu-right">
        <%= render 'profiles/menu', profile: @profile %>
      </td>
    </tr>
  </tbody>
</table>

app/views/topics/new.html.erb
<% title "Create Forum Topic for #{@profile.name}'s Profile" %>
<% description "Create forum topic for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, forum, topic" %>
<table class="activity-with-menu">
  <tbody>
    <tr>
      <td class="activity-with-menu-left">
        <h1><%= link_to @profile.name, profile_path(@profile) %></h1>
        <h2><%= link_to 'Forum', profile_topics_path(@profile) %></h2>
        <h3>New Topic</h3>

		<%= render 'form', topic: @topic %>

		<%= link_to 'Back', profile_topics_path(@profile) %>

      </td>
      <td class="activity-with-menu-right">
        <%= render 'profiles/menu', profile: @profile %>
      </td>
    </tr>
  </tbody>
</table>

app/views/topics/show.html.erb
<% title "View Forum Topic for #{@profile.name}'s Profile" %>
<% description "View forum topic for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, forum, topic" %>
<table class="activity-with-menu">
  <tbody>
    <tr>
      <td class="activity-with-menu-left">
        <h1><%= link_to @profile.name, profile_path(@profile) %></h1>
        <h2><%= link_to 'Forum', profile_topics_path(@profile) %></h2>
        <h3>Topic</h3>

        <p id="notice"><%= notice %></p>

        <table width="100%" border="1" class="forum">
          <thead>
            <tr>
              <td colspan="2" class="topic">
                <%= @topic.label %>
                <% if current_user && @topic.user == current_user %>
                  <%= link_to 'Edit', edit_profile_topic_path(@profile, @topic) %>
                <% end %>
              </td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="createdBy">
                <p>
                  <strong>Created by:</strong>
                  <%= @topic.user.name %>
                </p>
              </td>
              <td class="body">
                <p>
                  <%= @topic.message %>
                </p>
              </td>
            </tr>
            <% @topic.posts.each do |post| %>
              <tr>
                <td class="createdBy">
                  <p>
                    <strong>Created by:</strong>
                    <%= post.user.name %>
                  </p>
                </td>
                <td class="body">
                  <p>
                    <%= post.body %>
                  </p>

                  <% if current_user && post.user == current_user %>
                    <%= link_to 'Edit', edit_profile_topic_post_path(@profile, @topic, post) %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br />
        <%= link_to 'New Post', new_profile_topic_post_path(@profile, @topic) %>
         | <%= link_to 'View All Topics', profile_topics_path(@profile) %>

      </td>
      <td class="activity-with-menu-right">
        <%= render 'profiles/menu', profile: @profile %>
      </td>
    </tr>
  </tbody>
</table>