config/routes.rb
require 'subdomain'

Rails.application.routes.draw do
	get '/submit-image-to-profile' => 'photos#submit'
	post '/accept-image-to-profile' => 'photos#accept'

	resources :news
	resources :links
	resources :credits
	resources :entries
	resources :posts
	resources :topics
	resources :videos
	resources :screensavers
	resources :wallpapers

	devise_for :users, controllers: { 
		sessions: 'users/sessions', 
		registrations: 'users/registrations', 
		passwords: 'users/passwords' 
	}
	devise_for :admins, controllers: { 
		sessions: 'admins/sessions', 
		registrations: 'admins/registrations', 
		passwords: 'admins/passwords' 
	}

	resources :movies
	resources :tracks
	resources :photos
	resources :albums
#	resources :profiles
	
	# match '', to: 'blogs#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
	
#	constraints(Subdomain) do
#	    get '/' => 'profiles#show'
	    
	   
	    #resources :posts do
	    #  collection do
	    #    get :search
	    #  end
	    #end

		resources :profiles do
			resources :messages
	#		post 'contact', to: 'messages#create', as: 'create_message'
	#		get 'contact', to: 'messages#new', as: 'new_message'
		  	resources :movies
			resources :photos
			resources :albums do 
				resources :tracks
			end
			get 'filmography'
			get 'biography'
			get 'media'
			resources :wallpapers
			resources :screensavers
			resources :videos
			resources :topics do
				resources :posts
			end
			resources :entries
	 		resources :credits do
	 			get 'in'
	 			get 'out'
	 		end
			resources :links
			resources :news
		end

#	  end 

	# resources :profiles, constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' } do
	
	get 'home/index' #, :defaults => { :format => 'html' }
	get 'home/order' #, :defaults => { :format => 'html' }

	root 'profiles#index' #, :defaults => { :format => 'html' }

  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
	belongs_to :profile
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :set_profile, except: [:create]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Profile.find(params[:profile_id]).videos.paginate(:page => params[:page], :per_page => 50)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
    @video.profile = @profile if !@profile.nil?
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to profile_videos_url(@profile), notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    def set_profile
      @profile = !@video.nil? ? @video.profile : Profile.find(params[:profile_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :profile_id, :youtube_video_url)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :video_title %>
  </div>

  <div class="field">
    <%= form.label :profile_id %>
    <%= form.select :profile_id, Profile.pluck(:name, :id) %>
  </div>

  <div class="field">
    <%= form.label :youtube_video_url %>
    <%= form.text_field :youtube_video_url, id: :video_youtube_video_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<% title "Edit Videos for #{@profile.name}'s Profile" %>
<% description "Edit video media for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, media, videos, video" %>

<table class="activity-with-menu">
  <tbody>
    <tr>
      <td class="activity-with-menu-left" >
        <h1><%= link_to @profile.name, profile_path(@profile) %></h1>
        <h2><%= link_to 'Media', profile_media_path(@profile) %></h2>
        <h3><%= link_to 'Videos', profile_videos_path(@profile) %></h3>
		<h4>Editing Video</h4>

		<%= render 'form', video: @video %>

		<%= link_to 'Show Video', @video %> |
		<%= link_to 'View All Videos', profile_videos_path(@profile) %>


      </td>
      <td class="activity-with-menu-right">
        <%= render 'profiles/menu', profile: @profile %>
      </td>
    </tr>
  </tbody>
</table>

app/views/videos/index.html.erb
<% title "View All Videos for #{@profile.name}'s Profile" %>
<% description "View video media for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, media, videos, video" %>
<table class="activity-with-menu">
  <tbody>
    <tr>
      <td class="activity-with-menu-left">
        <h1><%= link_to @profile.name, profile_path(@profile) %></h1>
        <h2><%= link_to 'Media', profile_media_path(@profile) %></h2>
        <h3><%= link_to 'Videos', profile_videos_path(@profile) %></h3>
        <p id="notice"><%= notice %></p>
        
        <% if current_admin %>
          <%= link_to 'New Video', new_profile_video_path(@profile) %><br /><br />
        <% end %>
      
        <% @videos.each do |video| %>
          <div class="video">
          <% if !video.youtube_video_url.nil? %>
            <%= youtube_video_html(225, video.youtube_video_url).html_safe %>
            <br />          
            <%= link_to video.title, profile_video_path(@profile, video) %>
          <% end %>
          <br />
          <% if current_admin %>
            <%= link_to 'Edit Video', edit_profile_video_path(@profile, video) %>
             | <%= link_to 'Destroy Video', video, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          </div>
        <% end %>

      </td>
      <td class="activity-with-menu-right">
        <%= render 'profiles/menu', profile: @profile %>
      </td>
    </tr>
  </tbody>
</table>

app/views/videos/new.html.erb
<% title "New Video for #{@profile.name}'s Profile" %>
<% description "New video media for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, media, videos, video" %>
<table class="activity-with-menu">
  <tbody>
    <tr>
      <td class="activity-with-menu-left">
      	<h1><%= link_to @profile.name, profile_path(@profile) %></h1>
        <h2><%= link_to 'Media', profile_media_path(@profile) %></h2>
        <h3><%= link_to 'Videos', profile_videos_path(@profile) %></h3>
		<h4>New Video</h4>
		<%= render 'form', video: @video %>

		<%= link_to 'Back', profile_videos_path(@profile) %>
      </td>
      <td class="activity-with-menu-right">
        <%= render 'profiles/menu', profile: @profile %>
      </td>
    </tr>
  </tbody>
</table>

app/views/videos/show.html.erb
<% title "View Video for #{@profile.name}'s Profile" %>
<% description "View video media for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, media, videos, video" %>
<table class="activity-with-menu">
  <tbody>
    <tr>
      <td class="activity-with-menu-left">
      	<h1><%= link_to @profile.name, profile_path(@profile) %></h1>
        <h2><%= link_to 'Media', profile_media_path(@profile) %></h2>
        <h3><%= link_to 'Videos', profile_videos_path(@profile) %></h3>

		<p id="notice"><%= notice %></p>

		<p>
		  <strong>Title:</strong>
		  <%= @video.title %>
		</p>

		<p>
      <%= youtube_video_html(225, @video.youtube_video_url).html_safe %>
		</p>

		<%= link_to 'Edit', edit_profile_video_path(@profile, @video) %> |
		<%= link_to 'View All Videos', profile_videos_path(@profile) %>

      </td>
      <td class="activity-with-menu-right">
        <%= render 'profiles/menu', profile: @profile %>
      </td>
    </tr>
  </tbody>
</table>