config/routes.rb
require 'subdomain'

Rails.application.routes.draw do
	get '/submit-image-to-profile' => 'photos#submit'
	post '/accept-image-to-profile' => 'photos#accept'

	resources :news
	resources :links
	resources :credits
	resources :entries
	resources :posts
	resources :topics
	resources :videos
	resources :screensavers
	resources :wallpapers

	devise_for :users, controllers: { 
		sessions: 'users/sessions', 
		registrations: 'users/registrations', 
		passwords: 'users/passwords' 
	}
	devise_for :admins, controllers: { 
		sessions: 'admins/sessions', 
		registrations: 'admins/registrations', 
		passwords: 'admins/passwords' 
	}

	resources :movies
	resources :tracks
	resources :photos
	resources :albums
#	resources :profiles
	
	# match '', to: 'blogs#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
	
#	constraints(Subdomain) do
#	    get '/' => 'profiles#show'
	    
	   
	    #resources :posts do
	    #  collection do
	    #    get :search
	    #  end
	    #end

		resources :profiles do
			resources :messages
	#		post 'contact', to: 'messages#create', as: 'create_message'
	#		get 'contact', to: 'messages#new', as: 'new_message'
		  	resources :movies
			resources :photos
			resources :albums do 
				resources :tracks
			end
			get 'filmography'
			get 'biography'
			get 'media'
			resources :wallpapers
			resources :screensavers
			resources :videos
			resources :topics do
				resources :posts
			end
			resources :entries
	 		resources :credits do
	 			get 'in'
	 			get 'out'
	 		end
			resources :links
			resources :news
		end

#	  end 

	# resources :profiles, constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' } do
	
	get 'home/index' #, :defaults => { :format => 'html' }
	get 'home/order' #, :defaults => { :format => 'html' }

	root 'profiles#index' #, :defaults => { :format => 'html' }

  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/screensaver.rb
class Screensaver < ApplicationRecord
	belongs_to :profile
	has_attached_file :application
	validates_attachment_file_name :application, :matches => [/exe\Z/]
end

app/controllers/screensavers_controller.rb
class ScreensaversController < ApplicationController
  before_action :set_screensaver, only: [:show, :edit, :update, :destroy]
  before_action :set_profile, except: [:create]

  # GET /screensavers
  # GET /screensavers.json
  def index
    @screensavers = Profile.find(params[:profile_id]).screensavers.paginate(:page => params[:page], :per_page => 50)
  end

  # GET /screensavers/1
  # GET /screensavers/1.json
  def show
  end

  # GET /screensavers/new
  def new
    @screensaver = Screensaver.new
    @screensaver.profile = @profile if !@profile.nil?
  end

  # GET /screensavers/1/edit
  def edit
  end

  # POST /screensavers
  # POST /screensavers.json
  def create
    @screensaver = Screensaver.new(screensaver_params)

    respond_to do |format|
      if @screensaver.save
        format.html { redirect_to @screensaver, notice: 'Screensaver was successfully created.' }
        format.json { render :show, status: :created, location: @screensaver }
      else
        format.html { render :new }
        format.json { render json: @screensaver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screensavers/1
  # PATCH/PUT /screensavers/1.json
  def update
    respond_to do |format|
      if @screensaver.update(screensaver_params)
        format.html { redirect_to @screensaver, notice: 'Screensaver was successfully updated.' }
        format.json { render :show, status: :ok, location: @screensaver }
      else
        format.html { render :edit }
        format.json { render json: @screensaver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screensavers/1
  # DELETE /screensavers/1.json
  def destroy
    @screensaver.destroy
    respond_to do |format|
      format.html { redirect_to profile_screensavers_url(@profile), notice: 'Screensaver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screensaver
      @screensaver = Screensaver.find(params[:id])
    end

    def set_profile
      @profile = !@screensaver.nil? ? @screensaver.profile : Profile.find(params[:profile_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def screensaver_params
      params.require(:screensaver).permit(:title, :profile_id, :description, :application)
    end
end

app/helpers/screensavers_helper.rb
module ScreensaversHelper
end

app/views/screensavers/_form.html.erb
<%= form_with(model: screensaver, local: true) do |form| %>
  <% if screensaver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(screensaver.errors.count, "error") %> prohibited this screensaver from being saved:</h2>

      <ul>
      <% screensaver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :screensaver_title %>
  </div>

  <div class="field">
    <%= form.label :profile_id %>
    <%= form.select :profile_id, Profile.pluck(:name, :id) %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :screensaver_description %>
  </div>

  <div class="field">
    <%= form.label :application %>
    <%= form.file_field :application %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/screensavers/edit.html.erb
<% title "Edit Screensaver for #{@profile.name}'s Profile" %>
<% description "Edit screensaver media for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, media, screensaver, screensavers" %>
<table class="activity-with-menu">
  <tbody>
    <tr>
      <td class="activity-with-menu-left">
        <h1><%= link_to @profile.name, profile_path(@profile) %></h1>
        <h2><%= link_to 'Media', profile_media_path(@profile) %></h2>
        <h3><%= link_to 'ScreenSavers', profile_screensavers_path(@profile) %></h3>
        <h4>Editing ScreenSaver</h4>

		<%= render 'form', screensaver: @screensaver %>

		<%= link_to 'Show', profile_screensavers_path(@profile, @screensaver) %> |
		<%= link_to 'Back', profile_screensavers_path(@profile) %>
      </td>
      <td class="activity-with-menu-right">
        <%= render 'profiles/menu', profile: @profile %>
      </td>
    </tr>
  </tbody>
</table>

app/views/screensavers/index.html.erb
<% title "View Screensavers for #{@profile.name}'s Profile" %>
<% description "Show all screensaver media for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, media, screensaver, screensavers" %>
<table class="activity-with-menu">
  <tbody>
    <tr>
      <td class="activity-with-menu-left">
        <h1><%= link_to @profile.name, profile_path(@profile) %></h1>
        <h2><%= link_to 'Media', profile_media_path(@profile) %></h2>
        <h3><%= link_to 'ScreenSavers', profile_screensavers_path(@profile) %></h3>

        <% if current_admin %>
          <%= link_to 'New ScreenSaver', new_profile_screensaver_path %>
        <% end %>
        
        <p id="notice"><%= notice %></p>

        <table cellpadding="0" cellspacing="0">
          <tbody>
            <% @screensavers.each do |screensaver| %>
              <tr>
                <td valign="top" align="left">
                  <% if !screensaver.application.nil? %>
                    <%= link_to(screensaver.title, screensaver.application.url) %><br /><br />
                  <% else %>
                    <%= screensaver.title %>
                  <% end %>
                </td>
                <td valign="top" align="left">
                  <%= link_to 'Show', profile_screensaver_path(@profile, screensaver) %>
                  <% if current_admin %>
                   | <%= link_to 'Edit', edit_profile_screensaver_path(@profile, screensaver) %>
                   | <%= link_to 'Destroy', screensaver, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>


        <br />

      </td>
      <td class="activity-with-menu-right">
        <%= render 'profiles/menu', profile: @profile %>
      </td>
    </tr>
  </tbody>
</table>

app/views/screensavers/new.html.erb
<% title "New Screensaver for #{@profile.name}'s Profile" %>
<% description "New screensaver media for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, media, screensaver, screensavers" %>
<table class="activity-with-menu">
  <tbody>
    <tr>
      <td class="activity-with-menu-left">
      	<h1>New ScreenSaver</h1>

<%= render 'form', screensaver: @screensaver %>

<%= link_to 'Back', profile_screensavers_path(@profile) %>
      </td>
      <td class="activity-with-menu-right">
        <%= render 'profiles/menu', profile: @profile %>
      </td>
    </tr>
  </tbody>
</table>

app/views/screensavers/show.html.erb
<% title "View Screensaver for #{@profile.name}'s Profile" %>
<% description "View screensaver media for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, media, screensaver, screensavers" %>
<table class="activity-with-menu">
  <tbody>
    <tr>
      <td class="activity-with-menu-left">
      	<h1><%= link_to @profile.name, profile_path(@profile) %></h1>
        <h2><%= link_to 'Media', profile_media_path(@profile) %></h2>
        <h3><%= link_to 'Screensavers', profile_screensavers_path(@profile) %></h3>

		<p id="notice"><%= notice %></p>

		<div class="screensaver">
			<% if !@screensaver.application.nil? %>
				<%= link_to(@screensaver.title, @screensaver.application.url) %><br /><br />
			<% else %>
				<p>
				  <strong>Title:</strong>
				  <%= @screensaver.title %>
				</p>
			<% end %>

			<% if !@screensaver.description.nil? %>
			<p>
			  <%= @screensaver.description %>
			</p>
			<% end %>

			<%= link_to 'View All ScreenSavers', profile_screensavers_path(@profile) %>
			<% if current_admin %>
				 | <%= link_to 'Edit ScreenSaver', edit_profile_screensaver_path(@profile, @screensaver) %>
			<% end %>
		</div>
		
      </td>
      <td class="activity-with-menu-right">
        <%= render 'profiles/menu', profile: @profile %>
      </td>
    </tr>
  </tbody>
</table>