config/routes.rb
require 'subdomain'

Rails.application.routes.draw do
	get '/submit-image-to-profile' => 'photos#submit'
	post '/accept-image-to-profile' => 'photos#accept'

	resources :news
	resources :links
	resources :credits
	resources :entries
	resources :posts
	resources :topics
	resources :videos
	resources :screensavers
	resources :wallpapers

	devise_for :users, controllers: { 
		sessions: 'users/sessions', 
		registrations: 'users/registrations', 
		passwords: 'users/passwords' 
	}
	devise_for :admins, controllers: { 
		sessions: 'admins/sessions', 
		registrations: 'admins/registrations', 
		passwords: 'admins/passwords' 
	}

	resources :movies
	resources :tracks
	resources :photos
	resources :albums
#	resources :profiles
	
	# match '', to: 'blogs#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
	
#	constraints(Subdomain) do
#	    get '/' => 'profiles#show'
	    
	   
	    #resources :posts do
	    #  collection do
	    #    get :search
	    #  end
	    #end

		resources :profiles do
			resources :messages
	#		post 'contact', to: 'messages#create', as: 'create_message'
	#		get 'contact', to: 'messages#new', as: 'new_message'
		  	resources :movies
			resources :photos
			resources :albums do 
				resources :tracks
			end
			get 'filmography'
			get 'biography'
			get 'media'
			resources :wallpapers
			resources :screensavers
			resources :videos
			resources :topics do
				resources :posts
			end
			resources :entries
	 		resources :credits do
	 			get 'in'
	 			get 'out'
	 		end
			resources :links
			resources :news
		end

#	  end 

	# resources :profiles, constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' } do
	
	get 'home/index' #, :defaults => { :format => 'html' }
	get 'home/order' #, :defaults => { :format => 'html' }

	root 'profiles#index' #, :defaults => { :format => 'html' }

  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :topic
	belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :create, :new]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_topic, except: [:create]
  before_action :set_profile, except: [:create]
  before_action :verify_owner!, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    redirect_to profile_topic_path(@profile, @topic)  
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.topic = @topic if !@topic.nil?
    @post.user = User.find(current_user["id"]) if current_user
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = User.find(current_user["id"]) if current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to profile_topic_posts_path(@post.topic.profile, @post.topic), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to profile_topic_posts_path(@post.topic.profile, @post.topic), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_profile
      @profile = !@topic.nil? ? @topic.profile : Profile.find(params[:profile_id])
    end

    def set_topic
      @topic = !@post.nil? ? @post.topic : Topic.find(params[:topic_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :topic_id)
    end

    def verify_owner!
      puts "[[[]]] verify_owner! #{@topic.user.id} == #{current_user["id"]}"

      if @post.user.id != current_user["id"]
        flash[:notice] = "You are not the owner of this post"
        redirect_to profile_topic_path(@profile, @topic)
      end 
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <%= form.hidden_field :topic_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% title "Edit Forum Post for #{@profile.name}'s Profile" %>
<% description "Edit forum post for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, forum, post" %>
<table class="activity-with-menu">
  	<tbody>
    	<tr>
      		<td class="activity-with-menu-left">
      			<h1>Editing Post</h1>

          <table width="100%" border="1">
          <thead>
            <tr>
              <td colspan="2">
                <%= @post.topic.label %>
                <% if current_user && @topic.user == current_user %>
                  <%= link_to 'Edit', edit_profile_topic_path(@profile, @topic) %>
                <% end %>
              </td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <p>
                  <strong>Created by:</strong>
                  <%= @post.topic.user.name %>
                </p>
              </td>
              <td>
                <p>
                  <%= @post.topic.message %>
                </p>
              </td>
            </tr>
          </tbody>
        </table>

<%= render 'form', post: @post %>

<%= link_to 'Show', profile_topic_post_path(@profile, @topic, @post) %> |
<%= link_to 'Back', profile_topic_posts_path(@profile, @topic) %>
			</td>
      		<td class="activity-with-menu-right">
        		<%= render 'profiles/menu', profile: @profile %>
      		</td>
    	</tr>
  	</tbody>
</table>

app/views/posts/index.html.erb
<% title "View Forum Posts for #{@profile.name}'s Profile" %>
<% description "Viewing all Forum Posts for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, forum, post" %>
<table class="activity-with-menu">
    <tbody>
      <tr>
          <td class="activity-with-menu-left">
            <p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.body %></td>
        <td><%= post.topic_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
      </td>
          <td class="activity-with-menu-right">
            <%= render 'profiles/menu', profile: @profile %>
          </td>
      </tr>
    </tbody>
</table>

app/views/posts/new.html.erb
<% title "New Forum Post for #{@profile.name}'s Profile" %>
<% description "Create forum post for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, forum, post" %>
<table class="activity-with-menu">
    <tbody>
      <tr>
          <td class="activity-with-menu-left">
        <h1><%= link_to @profile.name, profile_path(@profile) %></h1>
        <h2><%= link_to 'Forum', profile_topics_path(@profile) %></h2>
        <h3>New Post</h3>
          <table width="100%" border="1" class="forum">
          <thead>
            <tr>
              <td colspan="2" class="topic">
                <%= @post.topic.label %>
                <% if current_user && @topic.user == current_user %>
                  <%= link_to 'Edit', edit_profile_topic_path(@profile, @topic) %>
                <% end %>
              </td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="createdBy">
                <p>
                  <strong>Created by:</strong>
                  <%= @post.topic.user.name %>
                </p>
              </td>
              <td class="body">
                <p>
                  <%= @post.topic.message %>
                </p>
              </td>
            </tr>
          </tbody>
        </table>
<%= render 'form', post: @post %>

		<%= link_to 'Back', profile_topic_posts_path(@profile, @topic) %>
			</td>
      		<td class="activity-with-menu-right">
        		<%= render 'profiles/menu', profile: @profile %>
      		</td>
    	</tr>
  	</tbody>
</table>

app/views/posts/show.html.erb
<% title "View Forum Post for #{@profile.name}'s Profile" %>
<% description "Viewing forum post for #{@profile.name}'s profile" %>
<% keywords "#{@profile.name}, forum, post" %>
<table class="activity-with-menu">
    <tbody>
      <tr>
          <td class="activity-with-menu-left">
          	<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @post.topic_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', profile_topic_posts_path(@profile, @topic) %>

			</td>
      		<td class="activity-with-menu-right">
        		<%= render 'profiles/menu', profile: @profile %>
      		</td>
    	</tr>
  	</tbody>
</table>